image: node:latest

before_script:
  - yarn install
  - ./node_modules/.bin/gatsby build --prefix-paths

build:
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -R -x ~partytown/ $LOCAL $SERVER --parallel=10; mirror -R $LOCAL/~partytown/ $SERVER --parallel=10"
  only:
    - main